/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as TasksNewRouteImport } from './routes/tasks/new'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as ProjectsSlugEditRouteImport } from './routes/projects/$slug.edit'
import { Route as ProjectsSlugTasksNewRouteImport } from './routes/projects/$slug.tasks.new'
import { Route as ProjectsSlugTasksTaskIdRouteImport } from './routes/projects/$slug.tasks.$taskId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksNewRoute = TasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugEditRoute = ProjectsSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProjectsSlugRoute,
} as any)
const ProjectsSlugTasksNewRoute = ProjectsSlugTasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => ProjectsSlugRoute,
} as any)
const ProjectsSlugTasksTaskIdRoute = ProjectsSlugTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => ProjectsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documentation': typeof DocumentationRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/projects/$slug': typeof ProjectsSlugRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/tasks/new': typeof TasksNewRoute
  '/projects/': typeof ProjectsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/projects/$slug/edit': typeof ProjectsSlugEditRoute
  '/projects/$slug/tasks/$taskId': typeof ProjectsSlugTasksTaskIdRoute
  '/projects/$slug/tasks/new': typeof ProjectsSlugTasksNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documentation': typeof DocumentationRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/projects/$slug': typeof ProjectsSlugRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/tasks/new': typeof TasksNewRoute
  '/projects': typeof ProjectsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/projects/$slug/edit': typeof ProjectsSlugEditRoute
  '/projects/$slug/tasks/$taskId': typeof ProjectsSlugTasksTaskIdRoute
  '/projects/$slug/tasks/new': typeof ProjectsSlugTasksNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/documentation': typeof DocumentationRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/projects/$slug': typeof ProjectsSlugRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/tasks/new': typeof TasksNewRoute
  '/projects/': typeof ProjectsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/projects/$slug/edit': typeof ProjectsSlugEditRoute
  '/projects/$slug/tasks/$taskId': typeof ProjectsSlugTasksTaskIdRoute
  '/projects/$slug/tasks/new': typeof ProjectsSlugTasksNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documentation'
    | '/login'
    | '/register'
    | '/search'
    | '/settings'
    | '/users'
    | '/projects/$slug'
    | '/projects/new'
    | '/tasks/new'
    | '/projects/'
    | '/tasks/'
    | '/projects/$slug/edit'
    | '/projects/$slug/tasks/$taskId'
    | '/projects/$slug/tasks/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/documentation'
    | '/login'
    | '/register'
    | '/search'
    | '/settings'
    | '/users'
    | '/projects/$slug'
    | '/projects/new'
    | '/tasks/new'
    | '/projects'
    | '/tasks'
    | '/projects/$slug/edit'
    | '/projects/$slug/tasks/$taskId'
    | '/projects/$slug/tasks/new'
  id:
    | '__root__'
    | '/'
    | '/documentation'
    | '/login'
    | '/register'
    | '/search'
    | '/settings'
    | '/users'
    | '/projects/$slug'
    | '/projects/new'
    | '/tasks/new'
    | '/projects/'
    | '/tasks/'
    | '/projects/$slug/edit'
    | '/projects/$slug/tasks/$taskId'
    | '/projects/$slug/tasks/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentationRoute: typeof DocumentationRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  ProjectsSlugRoute: typeof ProjectsSlugRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
  TasksNewRoute: typeof TasksNewRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/new': {
      id: '/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof TasksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug/edit': {
      id: '/projects/$slug/edit'
      path: '/edit'
      fullPath: '/projects/$slug/edit'
      preLoaderRoute: typeof ProjectsSlugEditRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
    '/projects/$slug/tasks/new': {
      id: '/projects/$slug/tasks/new'
      path: '/tasks/new'
      fullPath: '/projects/$slug/tasks/new'
      preLoaderRoute: typeof ProjectsSlugTasksNewRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
    '/projects/$slug/tasks/$taskId': {
      id: '/projects/$slug/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/projects/$slug/tasks/$taskId'
      preLoaderRoute: typeof ProjectsSlugTasksTaskIdRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
  }
}

interface ProjectsSlugRouteChildren {
  ProjectsSlugEditRoute: typeof ProjectsSlugEditRoute
  ProjectsSlugTasksTaskIdRoute: typeof ProjectsSlugTasksTaskIdRoute
  ProjectsSlugTasksNewRoute: typeof ProjectsSlugTasksNewRoute
}

const ProjectsSlugRouteChildren: ProjectsSlugRouteChildren = {
  ProjectsSlugEditRoute: ProjectsSlugEditRoute,
  ProjectsSlugTasksTaskIdRoute: ProjectsSlugTasksTaskIdRoute,
  ProjectsSlugTasksNewRoute: ProjectsSlugTasksNewRoute,
}

const ProjectsSlugRouteWithChildren = ProjectsSlugRoute._addFileChildren(
  ProjectsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentationRoute: DocumentationRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  ProjectsSlugRoute: ProjectsSlugRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
  TasksNewRoute: TasksNewRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
