/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyNewRouteImport } from './routes/company/new'
import { Route as CCompanySlugRouteImport } from './routes/c/$companySlug'
import { Route as CCompanySlugIndexRouteImport } from './routes/c/$companySlug/index'
import { Route as CCompanySlugTasksIndexRouteImport } from './routes/c/$companySlug/tasks/index'
import { Route as CCompanySlugProjectsIndexRouteImport } from './routes/c/$companySlug/projects/index'
import { Route as CCompanySlugTasksNewRouteImport } from './routes/c/$companySlug/tasks/new'
import { Route as CCompanySlugProjectsNewRouteImport } from './routes/c/$companySlug/projects/new'
import { Route as CCompanySlugProjectsProjectSlugRouteImport } from './routes/c/$companySlug/projects/$projectSlug'
import { Route as CCompanySlugProjectsProjectSlugEditRouteImport } from './routes/c/$companySlug/projects/$projectSlug.edit'
import { Route as CCompanySlugProjectsProjectSlugTasksNewRouteImport } from './routes/c/$companySlug/projects/$projectSlug.tasks.new'
import { Route as CCompanySlugProjectsProjectSlugTasksTaskIdRouteImport } from './routes/c/$companySlug/projects/$projectSlug.tasks.$taskId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyNewRoute = CompanyNewRouteImport.update({
  id: '/company/new',
  path: '/company/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CCompanySlugRoute = CCompanySlugRouteImport.update({
  id: '/c/$companySlug',
  path: '/c/$companySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CCompanySlugIndexRoute = CCompanySlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CCompanySlugRoute,
} as any)
const CCompanySlugTasksIndexRoute = CCompanySlugTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => CCompanySlugRoute,
} as any)
const CCompanySlugProjectsIndexRoute =
  CCompanySlugProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => CCompanySlugRoute,
  } as any)
const CCompanySlugTasksNewRoute = CCompanySlugTasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => CCompanySlugRoute,
} as any)
const CCompanySlugProjectsNewRoute = CCompanySlugProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => CCompanySlugRoute,
} as any)
const CCompanySlugProjectsProjectSlugRoute =
  CCompanySlugProjectsProjectSlugRouteImport.update({
    id: '/projects/$projectSlug',
    path: '/projects/$projectSlug',
    getParentRoute: () => CCompanySlugRoute,
  } as any)
const CCompanySlugProjectsProjectSlugEditRoute =
  CCompanySlugProjectsProjectSlugEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => CCompanySlugProjectsProjectSlugRoute,
  } as any)
const CCompanySlugProjectsProjectSlugTasksNewRoute =
  CCompanySlugProjectsProjectSlugTasksNewRouteImport.update({
    id: '/tasks/new',
    path: '/tasks/new',
    getParentRoute: () => CCompanySlugProjectsProjectSlugRoute,
  } as any)
const CCompanySlugProjectsProjectSlugTasksTaskIdRoute =
  CCompanySlugProjectsProjectSlugTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => CCompanySlugProjectsProjectSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documentation': typeof DocumentationRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/c/$companySlug': typeof CCompanySlugRouteWithChildren
  '/company/new': typeof CompanyNewRoute
  '/c/$companySlug/': typeof CCompanySlugIndexRoute
  '/c/$companySlug/projects/$projectSlug': typeof CCompanySlugProjectsProjectSlugRouteWithChildren
  '/c/$companySlug/projects/new': typeof CCompanySlugProjectsNewRoute
  '/c/$companySlug/tasks/new': typeof CCompanySlugTasksNewRoute
  '/c/$companySlug/projects/': typeof CCompanySlugProjectsIndexRoute
  '/c/$companySlug/tasks/': typeof CCompanySlugTasksIndexRoute
  '/c/$companySlug/projects/$projectSlug/edit': typeof CCompanySlugProjectsProjectSlugEditRoute
  '/c/$companySlug/projects/$projectSlug/tasks/$taskId': typeof CCompanySlugProjectsProjectSlugTasksTaskIdRoute
  '/c/$companySlug/projects/$projectSlug/tasks/new': typeof CCompanySlugProjectsProjectSlugTasksNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documentation': typeof DocumentationRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/company/new': typeof CompanyNewRoute
  '/c/$companySlug': typeof CCompanySlugIndexRoute
  '/c/$companySlug/projects/$projectSlug': typeof CCompanySlugProjectsProjectSlugRouteWithChildren
  '/c/$companySlug/projects/new': typeof CCompanySlugProjectsNewRoute
  '/c/$companySlug/tasks/new': typeof CCompanySlugTasksNewRoute
  '/c/$companySlug/projects': typeof CCompanySlugProjectsIndexRoute
  '/c/$companySlug/tasks': typeof CCompanySlugTasksIndexRoute
  '/c/$companySlug/projects/$projectSlug/edit': typeof CCompanySlugProjectsProjectSlugEditRoute
  '/c/$companySlug/projects/$projectSlug/tasks/$taskId': typeof CCompanySlugProjectsProjectSlugTasksTaskIdRoute
  '/c/$companySlug/projects/$projectSlug/tasks/new': typeof CCompanySlugProjectsProjectSlugTasksNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/documentation': typeof DocumentationRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/c/$companySlug': typeof CCompanySlugRouteWithChildren
  '/company/new': typeof CompanyNewRoute
  '/c/$companySlug/': typeof CCompanySlugIndexRoute
  '/c/$companySlug/projects/$projectSlug': typeof CCompanySlugProjectsProjectSlugRouteWithChildren
  '/c/$companySlug/projects/new': typeof CCompanySlugProjectsNewRoute
  '/c/$companySlug/tasks/new': typeof CCompanySlugTasksNewRoute
  '/c/$companySlug/projects/': typeof CCompanySlugProjectsIndexRoute
  '/c/$companySlug/tasks/': typeof CCompanySlugTasksIndexRoute
  '/c/$companySlug/projects/$projectSlug/edit': typeof CCompanySlugProjectsProjectSlugEditRoute
  '/c/$companySlug/projects/$projectSlug/tasks/$taskId': typeof CCompanySlugProjectsProjectSlugTasksTaskIdRoute
  '/c/$companySlug/projects/$projectSlug/tasks/new': typeof CCompanySlugProjectsProjectSlugTasksNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documentation'
    | '/login'
    | '/register'
    | '/settings'
    | '/users'
    | '/c/$companySlug'
    | '/company/new'
    | '/c/$companySlug/'
    | '/c/$companySlug/projects/$projectSlug'
    | '/c/$companySlug/projects/new'
    | '/c/$companySlug/tasks/new'
    | '/c/$companySlug/projects/'
    | '/c/$companySlug/tasks/'
    | '/c/$companySlug/projects/$projectSlug/edit'
    | '/c/$companySlug/projects/$projectSlug/tasks/$taskId'
    | '/c/$companySlug/projects/$projectSlug/tasks/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/documentation'
    | '/login'
    | '/register'
    | '/settings'
    | '/users'
    | '/company/new'
    | '/c/$companySlug'
    | '/c/$companySlug/projects/$projectSlug'
    | '/c/$companySlug/projects/new'
    | '/c/$companySlug/tasks/new'
    | '/c/$companySlug/projects'
    | '/c/$companySlug/tasks'
    | '/c/$companySlug/projects/$projectSlug/edit'
    | '/c/$companySlug/projects/$projectSlug/tasks/$taskId'
    | '/c/$companySlug/projects/$projectSlug/tasks/new'
  id:
    | '__root__'
    | '/'
    | '/documentation'
    | '/login'
    | '/register'
    | '/settings'
    | '/users'
    | '/c/$companySlug'
    | '/company/new'
    | '/c/$companySlug/'
    | '/c/$companySlug/projects/$projectSlug'
    | '/c/$companySlug/projects/new'
    | '/c/$companySlug/tasks/new'
    | '/c/$companySlug/projects/'
    | '/c/$companySlug/tasks/'
    | '/c/$companySlug/projects/$projectSlug/edit'
    | '/c/$companySlug/projects/$projectSlug/tasks/$taskId'
    | '/c/$companySlug/projects/$projectSlug/tasks/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentationRoute: typeof DocumentationRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  CCompanySlugRoute: typeof CCompanySlugRouteWithChildren
  CompanyNewRoute: typeof CompanyNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/new': {
      id: '/company/new'
      path: '/company/new'
      fullPath: '/company/new'
      preLoaderRoute: typeof CompanyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$companySlug': {
      id: '/c/$companySlug'
      path: '/c/$companySlug'
      fullPath: '/c/$companySlug'
      preLoaderRoute: typeof CCompanySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$companySlug/': {
      id: '/c/$companySlug/'
      path: '/'
      fullPath: '/c/$companySlug/'
      preLoaderRoute: typeof CCompanySlugIndexRouteImport
      parentRoute: typeof CCompanySlugRoute
    }
    '/c/$companySlug/tasks/': {
      id: '/c/$companySlug/tasks/'
      path: '/tasks'
      fullPath: '/c/$companySlug/tasks/'
      preLoaderRoute: typeof CCompanySlugTasksIndexRouteImport
      parentRoute: typeof CCompanySlugRoute
    }
    '/c/$companySlug/projects/': {
      id: '/c/$companySlug/projects/'
      path: '/projects'
      fullPath: '/c/$companySlug/projects/'
      preLoaderRoute: typeof CCompanySlugProjectsIndexRouteImport
      parentRoute: typeof CCompanySlugRoute
    }
    '/c/$companySlug/tasks/new': {
      id: '/c/$companySlug/tasks/new'
      path: '/tasks/new'
      fullPath: '/c/$companySlug/tasks/new'
      preLoaderRoute: typeof CCompanySlugTasksNewRouteImport
      parentRoute: typeof CCompanySlugRoute
    }
    '/c/$companySlug/projects/new': {
      id: '/c/$companySlug/projects/new'
      path: '/projects/new'
      fullPath: '/c/$companySlug/projects/new'
      preLoaderRoute: typeof CCompanySlugProjectsNewRouteImport
      parentRoute: typeof CCompanySlugRoute
    }
    '/c/$companySlug/projects/$projectSlug': {
      id: '/c/$companySlug/projects/$projectSlug'
      path: '/projects/$projectSlug'
      fullPath: '/c/$companySlug/projects/$projectSlug'
      preLoaderRoute: typeof CCompanySlugProjectsProjectSlugRouteImport
      parentRoute: typeof CCompanySlugRoute
    }
    '/c/$companySlug/projects/$projectSlug/edit': {
      id: '/c/$companySlug/projects/$projectSlug/edit'
      path: '/edit'
      fullPath: '/c/$companySlug/projects/$projectSlug/edit'
      preLoaderRoute: typeof CCompanySlugProjectsProjectSlugEditRouteImport
      parentRoute: typeof CCompanySlugProjectsProjectSlugRoute
    }
    '/c/$companySlug/projects/$projectSlug/tasks/new': {
      id: '/c/$companySlug/projects/$projectSlug/tasks/new'
      path: '/tasks/new'
      fullPath: '/c/$companySlug/projects/$projectSlug/tasks/new'
      preLoaderRoute: typeof CCompanySlugProjectsProjectSlugTasksNewRouteImport
      parentRoute: typeof CCompanySlugProjectsProjectSlugRoute
    }
    '/c/$companySlug/projects/$projectSlug/tasks/$taskId': {
      id: '/c/$companySlug/projects/$projectSlug/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/c/$companySlug/projects/$projectSlug/tasks/$taskId'
      preLoaderRoute: typeof CCompanySlugProjectsProjectSlugTasksTaskIdRouteImport
      parentRoute: typeof CCompanySlugProjectsProjectSlugRoute
    }
  }
}

interface CCompanySlugProjectsProjectSlugRouteChildren {
  CCompanySlugProjectsProjectSlugEditRoute: typeof CCompanySlugProjectsProjectSlugEditRoute
  CCompanySlugProjectsProjectSlugTasksTaskIdRoute: typeof CCompanySlugProjectsProjectSlugTasksTaskIdRoute
  CCompanySlugProjectsProjectSlugTasksNewRoute: typeof CCompanySlugProjectsProjectSlugTasksNewRoute
}

const CCompanySlugProjectsProjectSlugRouteChildren: CCompanySlugProjectsProjectSlugRouteChildren =
  {
    CCompanySlugProjectsProjectSlugEditRoute:
      CCompanySlugProjectsProjectSlugEditRoute,
    CCompanySlugProjectsProjectSlugTasksTaskIdRoute:
      CCompanySlugProjectsProjectSlugTasksTaskIdRoute,
    CCompanySlugProjectsProjectSlugTasksNewRoute:
      CCompanySlugProjectsProjectSlugTasksNewRoute,
  }

const CCompanySlugProjectsProjectSlugRouteWithChildren =
  CCompanySlugProjectsProjectSlugRoute._addFileChildren(
    CCompanySlugProjectsProjectSlugRouteChildren,
  )

interface CCompanySlugRouteChildren {
  CCompanySlugIndexRoute: typeof CCompanySlugIndexRoute
  CCompanySlugProjectsProjectSlugRoute: typeof CCompanySlugProjectsProjectSlugRouteWithChildren
  CCompanySlugProjectsNewRoute: typeof CCompanySlugProjectsNewRoute
  CCompanySlugTasksNewRoute: typeof CCompanySlugTasksNewRoute
  CCompanySlugProjectsIndexRoute: typeof CCompanySlugProjectsIndexRoute
  CCompanySlugTasksIndexRoute: typeof CCompanySlugTasksIndexRoute
}

const CCompanySlugRouteChildren: CCompanySlugRouteChildren = {
  CCompanySlugIndexRoute: CCompanySlugIndexRoute,
  CCompanySlugProjectsProjectSlugRoute:
    CCompanySlugProjectsProjectSlugRouteWithChildren,
  CCompanySlugProjectsNewRoute: CCompanySlugProjectsNewRoute,
  CCompanySlugTasksNewRoute: CCompanySlugTasksNewRoute,
  CCompanySlugProjectsIndexRoute: CCompanySlugProjectsIndexRoute,
  CCompanySlugTasksIndexRoute: CCompanySlugTasksIndexRoute,
}

const CCompanySlugRouteWithChildren = CCompanySlugRoute._addFileChildren(
  CCompanySlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentationRoute: DocumentationRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  CCompanySlugRoute: CCompanySlugRouteWithChildren,
  CompanyNewRoute: CompanyNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
